/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as InviteInvitationIdRouteImport } from './routes/invite/$invitationId'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProjectsProjectSlugSettingsRouteImport } from './routes/projects/$projectSlug/settings'
import { Route as ProjectsProjectSlugWorkspacesWorkspaceIdRouteImport } from './routes/projects/$projectSlug/workspaces/$workspaceId'
import { Route as ProjectsProjectSlugWorkspacesNewRouteImport } from './routes/projects/$projectSlug/workspaces/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSlugSettingsRoute =
  ProjectsProjectSlugSettingsRouteImport.update({
    id: '/projects/$projectSlug/settings',
    path: '/projects/$projectSlug/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectSlugWorkspacesWorkspaceIdRoute =
  ProjectsProjectSlugWorkspacesWorkspaceIdRouteImport.update({
    id: '/projects/$projectSlug/workspaces/$workspaceId',
    path: '/projects/$projectSlug/workspaces/$workspaceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectSlugWorkspacesNewRoute =
  ProjectsProjectSlugWorkspacesNewRouteImport.update({
    id: '/projects/$projectSlug/workspaces/new',
    path: '/projects/$projectSlug/workspaces/new',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$projectSlug/settings': typeof ProjectsProjectSlugSettingsRoute
  '/projects/$projectSlug/workspaces/$workspaceId': typeof ProjectsProjectSlugWorkspacesWorkspaceIdRoute
  '/projects/$projectSlug/workspaces/new': typeof ProjectsProjectSlugWorkspacesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$projectSlug/settings': typeof ProjectsProjectSlugSettingsRoute
  '/projects/$projectSlug/workspaces/$workspaceId': typeof ProjectsProjectSlugWorkspacesWorkspaceIdRoute
  '/projects/$projectSlug/workspaces/new': typeof ProjectsProjectSlugWorkspacesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$projectSlug/settings': typeof ProjectsProjectSlugSettingsRoute
  '/projects/$projectSlug/workspaces/$workspaceId': typeof ProjectsProjectSlugWorkspacesWorkspaceIdRoute
  '/projects/$projectSlug/workspaces/new': typeof ProjectsProjectSlugWorkspacesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/settings'
    | '/setup'
    | '/invite/$invitationId'
    | '/projects/new'
    | '/api/auth/$'
    | '/projects/$projectSlug/settings'
    | '/projects/$projectSlug/workspaces/$workspaceId'
    | '/projects/$projectSlug/workspaces/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/settings'
    | '/setup'
    | '/invite/$invitationId'
    | '/projects/new'
    | '/api/auth/$'
    | '/projects/$projectSlug/settings'
    | '/projects/$projectSlug/workspaces/$workspaceId'
    | '/projects/$projectSlug/workspaces/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/settings'
    | '/setup'
    | '/invite/$invitationId'
    | '/projects/new'
    | '/api/auth/$'
    | '/projects/$projectSlug/settings'
    | '/projects/$projectSlug/workspaces/$workspaceId'
    | '/projects/$projectSlug/workspaces/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ProjectsProjectSlugSettingsRoute: typeof ProjectsProjectSlugSettingsRoute
  ProjectsProjectSlugWorkspacesWorkspaceIdRoute: typeof ProjectsProjectSlugWorkspacesWorkspaceIdRoute
  ProjectsProjectSlugWorkspacesNewRoute: typeof ProjectsProjectSlugWorkspacesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug/settings': {
      id: '/projects/$projectSlug/settings'
      path: '/projects/$projectSlug/settings'
      fullPath: '/projects/$projectSlug/settings'
      preLoaderRoute: typeof ProjectsProjectSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug/workspaces/$workspaceId': {
      id: '/projects/$projectSlug/workspaces/$workspaceId'
      path: '/projects/$projectSlug/workspaces/$workspaceId'
      fullPath: '/projects/$projectSlug/workspaces/$workspaceId'
      preLoaderRoute: typeof ProjectsProjectSlugWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug/workspaces/new': {
      id: '/projects/$projectSlug/workspaces/new'
      path: '/projects/$projectSlug/workspaces/new'
      fullPath: '/projects/$projectSlug/workspaces/new'
      preLoaderRoute: typeof ProjectsProjectSlugWorkspacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ProjectsProjectSlugSettingsRoute: ProjectsProjectSlugSettingsRoute,
  ProjectsProjectSlugWorkspacesWorkspaceIdRoute:
    ProjectsProjectSlugWorkspacesWorkspaceIdRoute,
  ProjectsProjectSlugWorkspacesNewRoute: ProjectsProjectSlugWorkspacesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
