/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as OrganizationsNewRouteImport } from './routes/organizations/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OrganizationsOrganizationSlugIndexRouteImport } from './routes/organizations/$organizationSlug/index'
import { Route as OrganizationsOrganizationSlugSettingsRouteImport } from './routes/organizations/$organizationSlug/settings'
import { Route as OrganizationsOrganizationSlugProjectsNewRouteImport } from './routes/organizations/$organizationSlug/projects/new'
import { Route as OrganizationsOrganizationSlugProjectsProjectSlugSettingsRouteImport } from './routes/organizations/$organizationSlug/projects/$projectSlug/settings'
import { Route as OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesWorkspaceIdRouteImport } from './routes/organizations/$organizationSlug/projects/$projectSlug/workspaces/$workspaceId'
import { Route as OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesNewRouteImport } from './routes/organizations/$organizationSlug/projects/$projectSlug/workspaces/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrganizationSlugIndexRoute =
  OrganizationsOrganizationSlugIndexRouteImport.update({
    id: '/organizations/$organizationSlug/',
    path: '/organizations/$organizationSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationSlugSettingsRoute =
  OrganizationsOrganizationSlugSettingsRouteImport.update({
    id: '/organizations/$organizationSlug/settings',
    path: '/organizations/$organizationSlug/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationSlugProjectsNewRoute =
  OrganizationsOrganizationSlugProjectsNewRouteImport.update({
    id: '/organizations/$organizationSlug/projects/new',
    path: '/organizations/$organizationSlug/projects/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationSlugProjectsProjectSlugSettingsRoute =
  OrganizationsOrganizationSlugProjectsProjectSlugSettingsRouteImport.update({
    id: '/organizations/$organizationSlug/projects/$projectSlug/settings',
    path: '/organizations/$organizationSlug/projects/$projectSlug/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesWorkspaceIdRoute =
  OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesWorkspaceIdRouteImport.update(
    {
      id: '/organizations/$organizationSlug/projects/$projectSlug/workspaces/$workspaceId',
      path: '/organizations/$organizationSlug/projects/$projectSlug/workspaces/$workspaceId',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesNewRoute =
  OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesNewRouteImport.update(
    {
      id: '/organizations/$organizationSlug/projects/$projectSlug/workspaces/new',
      path: '/organizations/$organizationSlug/projects/$projectSlug/workspaces/new',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations/$organizationSlug/settings': typeof OrganizationsOrganizationSlugSettingsRoute
  '/organizations/$organizationSlug/': typeof OrganizationsOrganizationSlugIndexRoute
  '/organizations/$organizationSlug/projects/new': typeof OrganizationsOrganizationSlugProjectsNewRoute
  '/organizations/$organizationSlug/projects/$projectSlug/settings': typeof OrganizationsOrganizationSlugProjectsProjectSlugSettingsRoute
  '/organizations/$organizationSlug/projects/$projectSlug/workspaces/$workspaceId': typeof OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesWorkspaceIdRoute
  '/organizations/$organizationSlug/projects/$projectSlug/workspaces/new': typeof OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations/$organizationSlug/settings': typeof OrganizationsOrganizationSlugSettingsRoute
  '/organizations/$organizationSlug': typeof OrganizationsOrganizationSlugIndexRoute
  '/organizations/$organizationSlug/projects/new': typeof OrganizationsOrganizationSlugProjectsNewRoute
  '/organizations/$organizationSlug/projects/$projectSlug/settings': typeof OrganizationsOrganizationSlugProjectsProjectSlugSettingsRoute
  '/organizations/$organizationSlug/projects/$projectSlug/workspaces/$workspaceId': typeof OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesWorkspaceIdRoute
  '/organizations/$organizationSlug/projects/$projectSlug/workspaces/new': typeof OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations/$organizationSlug/settings': typeof OrganizationsOrganizationSlugSettingsRoute
  '/organizations/$organizationSlug/': typeof OrganizationsOrganizationSlugIndexRoute
  '/organizations/$organizationSlug/projects/new': typeof OrganizationsOrganizationSlugProjectsNewRoute
  '/organizations/$organizationSlug/projects/$projectSlug/settings': typeof OrganizationsOrganizationSlugProjectsProjectSlugSettingsRoute
  '/organizations/$organizationSlug/projects/$projectSlug/workspaces/$workspaceId': typeof OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesWorkspaceIdRoute
  '/organizations/$organizationSlug/projects/$projectSlug/workspaces/new': typeof OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/organizations/new'
    | '/organizations/'
    | '/api/auth/$'
    | '/organizations/$organizationSlug/settings'
    | '/organizations/$organizationSlug/'
    | '/organizations/$organizationSlug/projects/new'
    | '/organizations/$organizationSlug/projects/$projectSlug/settings'
    | '/organizations/$organizationSlug/projects/$projectSlug/workspaces/$workspaceId'
    | '/organizations/$organizationSlug/projects/$projectSlug/workspaces/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/organizations/new'
    | '/organizations'
    | '/api/auth/$'
    | '/organizations/$organizationSlug/settings'
    | '/organizations/$organizationSlug'
    | '/organizations/$organizationSlug/projects/new'
    | '/organizations/$organizationSlug/projects/$projectSlug/settings'
    | '/organizations/$organizationSlug/projects/$projectSlug/workspaces/$workspaceId'
    | '/organizations/$organizationSlug/projects/$projectSlug/workspaces/new'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/organizations/new'
    | '/organizations/'
    | '/api/auth/$'
    | '/organizations/$organizationSlug/settings'
    | '/organizations/$organizationSlug/'
    | '/organizations/$organizationSlug/projects/new'
    | '/organizations/$organizationSlug/projects/$projectSlug/settings'
    | '/organizations/$organizationSlug/projects/$projectSlug/workspaces/$workspaceId'
    | '/organizations/$organizationSlug/projects/$projectSlug/workspaces/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OrganizationsOrganizationSlugSettingsRoute: typeof OrganizationsOrganizationSlugSettingsRoute
  OrganizationsOrganizationSlugIndexRoute: typeof OrganizationsOrganizationSlugIndexRoute
  OrganizationsOrganizationSlugProjectsNewRoute: typeof OrganizationsOrganizationSlugProjectsNewRoute
  OrganizationsOrganizationSlugProjectsProjectSlugSettingsRoute: typeof OrganizationsOrganizationSlugProjectsProjectSlugSettingsRoute
  OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesWorkspaceIdRoute: typeof OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesWorkspaceIdRoute
  OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesNewRoute: typeof OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationSlug/': {
      id: '/organizations/$organizationSlug/'
      path: '/organizations/$organizationSlug'
      fullPath: '/organizations/$organizationSlug/'
      preLoaderRoute: typeof OrganizationsOrganizationSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationSlug/settings': {
      id: '/organizations/$organizationSlug/settings'
      path: '/organizations/$organizationSlug/settings'
      fullPath: '/organizations/$organizationSlug/settings'
      preLoaderRoute: typeof OrganizationsOrganizationSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationSlug/projects/new': {
      id: '/organizations/$organizationSlug/projects/new'
      path: '/organizations/$organizationSlug/projects/new'
      fullPath: '/organizations/$organizationSlug/projects/new'
      preLoaderRoute: typeof OrganizationsOrganizationSlugProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationSlug/projects/$projectSlug/settings': {
      id: '/organizations/$organizationSlug/projects/$projectSlug/settings'
      path: '/organizations/$organizationSlug/projects/$projectSlug/settings'
      fullPath: '/organizations/$organizationSlug/projects/$projectSlug/settings'
      preLoaderRoute: typeof OrganizationsOrganizationSlugProjectsProjectSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationSlug/projects/$projectSlug/workspaces/$workspaceId': {
      id: '/organizations/$organizationSlug/projects/$projectSlug/workspaces/$workspaceId'
      path: '/organizations/$organizationSlug/projects/$projectSlug/workspaces/$workspaceId'
      fullPath: '/organizations/$organizationSlug/projects/$projectSlug/workspaces/$workspaceId'
      preLoaderRoute: typeof OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationSlug/projects/$projectSlug/workspaces/new': {
      id: '/organizations/$organizationSlug/projects/$projectSlug/workspaces/new'
      path: '/organizations/$organizationSlug/projects/$projectSlug/workspaces/new'
      fullPath: '/organizations/$organizationSlug/projects/$projectSlug/workspaces/new'
      preLoaderRoute: typeof OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  OrganizationsNewRoute: OrganizationsNewRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OrganizationsOrganizationSlugSettingsRoute:
    OrganizationsOrganizationSlugSettingsRoute,
  OrganizationsOrganizationSlugIndexRoute:
    OrganizationsOrganizationSlugIndexRoute,
  OrganizationsOrganizationSlugProjectsNewRoute:
    OrganizationsOrganizationSlugProjectsNewRoute,
  OrganizationsOrganizationSlugProjectsProjectSlugSettingsRoute:
    OrganizationsOrganizationSlugProjectsProjectSlugSettingsRoute,
  OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesWorkspaceIdRoute:
    OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesWorkspaceIdRoute,
  OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesNewRoute:
    OrganizationsOrganizationSlugProjectsProjectSlugWorkspacesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
