/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as OrganizationsNewRouteImport } from './routes/organizations/new'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces/$workspaceId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OrganizationsOrganizationIdSettingsRouteImport } from './routes/organizations/$organizationId/settings'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as OrganizationsOrganizationIdProjectsNewRouteImport } from './routes/organizations/$organizationId/projects/new'
import { Route as ProjectsProjectIdWorkspacesNewRouteImport } from './routes/projects/$projectId/workspaces/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrganizationIdSettingsRoute =
  OrganizationsOrganizationIdSettingsRouteImport.update({
    id: '/organizations/$organizationId/settings',
    path: '/organizations/$organizationId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdProjectsNewRoute =
  OrganizationsOrganizationIdProjectsNewRouteImport.update({
    id: '/organizations/$organizationId/projects/new',
    path: '/organizations/$organizationId/projects/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdWorkspacesNewRoute =
  ProjectsProjectIdWorkspacesNewRouteImport.update({
    id: '/projects/$projectId/workspaces/new',
    path: '/projects/$projectId/workspaces/new',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/organizations/$organizationId/projects/new': typeof OrganizationsOrganizationIdProjectsNewRoute
  '/projects/$projectId/workspaces/new': typeof ProjectsProjectIdWorkspacesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/organizations/$organizationId/projects/new': typeof OrganizationsOrganizationIdProjectsNewRoute
  '/projects/$projectId/workspaces/new': typeof ProjectsProjectIdWorkspacesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/organizations/$organizationId/projects/new': typeof OrganizationsOrganizationIdProjectsNewRoute
  '/projects/$projectId/workspaces/new': typeof ProjectsProjectIdWorkspacesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organizations/new'
    | '/workspaces/$workspaceId'
    | '/organizations/'
    | '/api/auth/$'
    | '/organizations/$organizationId/settings'
    | '/projects/$projectId/settings'
    | '/organizations/$organizationId/projects/new'
    | '/projects/$projectId/workspaces/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/organizations/new'
    | '/workspaces/$workspaceId'
    | '/organizations'
    | '/api/auth/$'
    | '/organizations/$organizationId/settings'
    | '/projects/$projectId/settings'
    | '/organizations/$organizationId/projects/new'
    | '/projects/$projectId/workspaces/new'
  id:
    | '__root__'
    | '/'
    | '/organizations/new'
    | '/workspaces/$workspaceId'
    | '/organizations/'
    | '/api/auth/$'
    | '/organizations/$organizationId/settings'
    | '/projects/$projectId/settings'
    | '/organizations/$organizationId/projects/new'
    | '/projects/$projectId/workspaces/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OrganizationsOrganizationIdSettingsRoute: typeof OrganizationsOrganizationIdSettingsRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  OrganizationsOrganizationIdProjectsNewRoute: typeof OrganizationsOrganizationIdProjectsNewRoute
  ProjectsProjectIdWorkspacesNewRoute: typeof ProjectsProjectIdWorkspacesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/settings': {
      id: '/organizations/$organizationId/settings'
      path: '/organizations/$organizationId/settings'
      fullPath: '/organizations/$organizationId/settings'
      preLoaderRoute: typeof OrganizationsOrganizationIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/projects/new': {
      id: '/organizations/$organizationId/projects/new'
      path: '/organizations/$organizationId/projects/new'
      fullPath: '/organizations/$organizationId/projects/new'
      preLoaderRoute: typeof OrganizationsOrganizationIdProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/workspaces/new': {
      id: '/projects/$projectId/workspaces/new'
      path: '/projects/$projectId/workspaces/new'
      fullPath: '/projects/$projectId/workspaces/new'
      preLoaderRoute: typeof ProjectsProjectIdWorkspacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizationsNewRoute: OrganizationsNewRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OrganizationsOrganizationIdSettingsRoute:
    OrganizationsOrganizationIdSettingsRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  OrganizationsOrganizationIdProjectsNewRoute:
    OrganizationsOrganizationIdProjectsNewRoute,
  ProjectsProjectIdWorkspacesNewRoute: ProjectsProjectIdWorkspacesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
