#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
USE_EXISTING_ENV_VALUES="${USE_EXISTING_ENV_VALUES:-true}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1 && tput clear 2>/dev/null; then return 0; fi
  printf '\033[2J\033[3J\033[H'
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ "$USE_EXISTING_ENV_VALUES" == "true" ]] || return 1
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
banner "Set up Sylph"

stage "Prepare your machine"
say "This is the local alternative to browser setup through GitHub Actions."
for tool in bun docker openssl git; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    warn "$tool is required. Install it, or follow browser setup in docs/operators.md."
    exit 1
  fi
done
if ! docker info >/dev/null 2>&1; then
  warn "Start Docker, then run setup again."
  exit 1
fi
bun install --frozen-lockfile
note "Existing values in $ENV_FILE are reused. Press Enter to keep them."

stage "Connect Cloudflare"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
ask CLOUDFLARE_ACCOUNT_ID "Cloudflare Account ID:"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
ask SYLPH_DOMAIN "Custom hostname, or enter workers.dev for a Cloudflare address:"
if [[ "$SYLPH_DOMAIN" == "workers.dev" ]]; then SYLPH_DOMAIN=""; fi
write_env SYLPH_DOMAIN "$SYLPH_DOMAIN"
CLOUDFLARE_API_TOKEN=$(_existing CLOUDFLARE_API_TOKEN || true)
if [[ -z "$CLOUDFLARE_API_TOKEN" ]]; then
  open_url "https://dash.cloudflare.com/?to=/:account/api-tokens"
  step "Create an account API token named Sylph deploy for this account."
  step "Add Account Settings Read, Account API Tokens Write, Workers Scripts Write, D1 Write, Workers R2 Storage Write, Workers Containers Write, Workers CI Write, Workers AI Read, Workers AI Write, Artifacts Write, and Browser Run Write."
  if [[ -n "$SYLPH_DOMAIN" ]]; then
    step "Also grant Zone Read and DNS Read for the custom domain's zone."
  fi
  ask_secret CLOUDFLARE_API_TOKEN "Cloudflare deploy token:"
else
  note "Reusing the saved deploy token."
fi
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
export CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_API_TOKEN SYLPH_DOMAIN
CI=true bunx alchemy login --configure

stage "Protect setup"
INSTALLATION_CLAIM_SECRET=$(_existing INSTALLATION_CLAIM_SECRET || true)
if [[ -z "$INSTALLATION_CLAIM_SECRET" ]]; then
  INSTALLATION_CLAIM_SECRET=$(openssl rand -hex 32)
fi
write_env INSTALLATION_CLAIM_SECRET "$INSTALLATION_CLAIM_SECRET"
write_env ALLOW_TEST_MAGIC_LINKS "false"
export INSTALLATION_CLAIM_SECRET
say "Your setup code is saved as INSTALLATION_CLAIM_SECRET in $ENV_FILE. Keep it for the browser setup step."
note "Alchemy creates and retains the other credentials automatically. Existing credential overrides are reused."
bun scripts/deploy-check.ts

stage "Deploy Sylph"
if ! confirm "Deploy Sylph to your Cloudflare account now?"; then
  note "Your settings are saved. Run setup again when ready."
  exit 0
fi
deploy_log=$(mktemp)
bun alchemy deploy --stage prod --yes 2>&1 | tee "$deploy_log"
bun scripts/deploy-result.mjs "$deploy_log"
SYLPH_URL=$(sed -nE "s/.*websiteUrl[^h]*(https:[^'\" ,}]+).*/\1/p" "$deploy_log" | tail -n1)
rm -f "$deploy_log"
if [[ -z "$SYLPH_URL" ]]; then
  warn "The deployment did not report its URL. Review the deployment output."
  exit 1
fi
open_url "${SYLPH_URL%/}/setup"
say "Enter your setup code in the browser, connect GitHub, sign in, and name your Organization."
pause "Press Enter after you have claimed the Installation in the browser."

stage "Enable updates"
note "GitHub Actions settings will be saved to $(git remote get-url origin)."
if confirm "Save deployment settings to this repository's GitHub Actions?"; then
  for name in CLOUDFLARE_API_TOKEN INSTALLATION_CLAIM_SECRET BETTER_AUTH_SECRET CREDENTIAL_ENCRYPTION_KEY CF_TOKEN R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY GITHUB_CLIENT_SECRET OAUTH_PROXY_SECRET; do
    value=$(_existing "$name" || true)
    if [[ -n "$value" ]]; then set_secret "$name" "$value"; fi
  done
  set_var SYLPH_DOMAIN "$SYLPH_DOMAIN"
  for name in CLOUDFLARE_ACCOUNT_ID GITHUB_CLIENT_ID OAUTH_PROXY_URL OAUTH_PROXY_TRUSTED_ORIGINS; do
    value=$(_existing "$name" || true)
    if [[ -n "$value" ]]; then set_var "$name" "$value"; fi
  done
fi
say "Push updates to main or run Deploy production in GitHub Actions. Use the same account and deployment state to preserve credentials."
finish
