#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
USE_EXISTING_ENV_VALUES="${USE_EXISTING_ENV_VALUES:-true}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1 && tput clear 2>/dev/null; then return 0; fi
  printf '\033[2J\033[3J\033[H'
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ "$USE_EXISTING_ENV_VALUES" == "true" ]] || return 1
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

CLOUDFLARE_API="https://api.cloudflare.com/client/v4"
DEPLOY_TOKEN_PERMISSIONS="Account Settings Read, Account API Tokens Write, Workers Scripts Write, D1 Write, Workers R2 Storage Write, Workers Containers Write, Workers CI Write, Workers AI Read, Workers AI Write, Artifacts Write, and Browser Run Write."
RUNTIME_TOKEN_PERMISSIONS="Account Settings Read,Workers Scripts Write,D1 Write,Workers R2 Storage Write,Workers Containers Write,Workers CI Write,Workers AI Read,Workers AI Write"
R2_TOKEN_PERMISSIONS="Workers R2 Storage Write"

ok() { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

require_tool() {
  if command -v "$1" >/dev/null 2>&1; then ok "$2"; return 0; fi
  warn "$3"
  return 1
}

cloudflare_get() {
  curl --silent --show-error --header "Authorization: Bearer $CLOUDFLARE_API_TOKEN" "$CLOUDFLARE_API$1"
}

cloudflare_field() {
  bun -e '
    const body = JSON.parse(await Bun.stdin.text())
    let value = body
    for (const key of process.argv[1].split(".")) value = value?.[key]
    if (!body.success || value === undefined || value === null) {
      const detail = body.errors?.map((error) => error.message).join("; ")
      console.error(detail || `Cloudflare did not return ${process.argv[1]}`)
      process.exit(1)
    }
    process.stdout.write(String(value))
  ' "$1"
}

json_field() {
  bun -e '
    const body = JSON.parse(await Bun.stdin.text())
    process.stdout.write(String(body[process.argv[1]] ?? ""))
  ' "$1"
}

alchemy_profile_method() {
  bun -e '
    const file = Bun.file(`${process.env.HOME}/.alchemy/profiles.json`)
    const config = (await file.exists()) ? await file.json() : { profiles: {} }
    process.stdout.write(config.profiles?.default?.Cloudflare?.method ?? "")
  '
}

deploy_url_from_log() {
  sed -nE "s/.*websiteUrl[^h]*(https:[^'\" ,}]+).*/\1/p" "$1" | tail -n1
}

timestamp() { date -u +%Y-%m-%dT%H:%M:%SZ; }

banner "Sylph Installation setup"

if [[ -f "$ENV_FILE" ]]; then
  say "Setup found existing values in $ENV_FILE."
  if confirm "Reuse these values as defaults?"; then
    USE_EXISTING_ENV_VALUES="true"
    note "Existing values will be reused when you leave an answer blank."
  else
    USE_EXISTING_ENV_VALUES="false"
    note "Existing values will be ignored. New answers will replace matching values in $ENV_FILE."
  fi
  pause "Press Enter to continue."
fi

stage "Preflight"
say "Sylph deploys from your own fork of the repository into your own Cloudflare account."
missing=0
require_tool bun "Bun $(bun --version 2>/dev/null || true)" "Bun is required: https://bun.sh" || missing=1
require_tool docker "Docker" "Docker is required because Alchemy pulls the CI sandbox image and pushes it to your account: https://docs.docker.com/get-docker/" || missing=1
require_tool openssl "OpenSSL" "OpenSSL is required to generate secrets." || missing=1
require_tool curl "curl" "curl is required to talk to the Cloudflare API." || missing=1
require_tool git "git" "git is required." || missing=1
if command -v docker >/dev/null 2>&1 && ! docker info >/dev/null 2>&1; then
  warn "Docker is installed but not running. Start it before the deployment stage."
fi
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  ok "gh is authenticated, so production secrets can be published automatically"
else
  note "gh is not ready. The production automation stage will list the secrets to set by hand."
fi
origin_url=$(git remote get-url origin 2>/dev/null || true)
if [[ "$origin_url" == *github.com[:/]kcc989/sylph* ]]; then
  warn "origin points at the upstream repository. Fork Sylph and clone your fork so GitHub Actions deploys from a repository you control."
else
  note "Deploying from $origin_url"
fi
note "Your fork's main branch deploys through GitHub Actions. Upgrade by syncing the fork with upstream."
if (( missing )); then
  warn "Install the missing tools, then re-run ./scripts/setup.sh"
  exit 1
fi
pause "Prerequisites are present. Press Enter to continue."

stage "Cloudflare deploy token"
say "One account-owned API token deploys Sylph from this machine and from GitHub Actions."
say "It also mints the narrower credentials the deployed Worker uses, so the Worker never holds a token that can create tokens."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Copy the Account ID shown on the right of the Workers & Pages overview."
ask CLOUDFLARE_ACCOUNT_ID "Paste the Cloudflare Account ID:"
CLOUDFLARE_API_TOKEN=$(_existing CLOUDFLARE_API_TOKEN || true)
if [[ -z "$CLOUDFLARE_API_TOKEN" ]]; then
  open_url "https://dash.cloudflare.com/?to=/:account/api-tokens"
  step "Choose Create Token, then Create Custom Token, and name it Sylph deploy."
  step "Under Account permissions, add $DEPLOY_TOKEN_PERMISSIONS"
  step "Under Account Resources, choose Include, Specific account, then select only this Sylph Installation's account. Do not add zone resources."
  step "Create the token, then copy its value. Cloudflare shows it only once."
  ask_secret CLOUDFLARE_API_TOKEN "Paste the Cloudflare deploy token:"
else
  note "Reusing the Cloudflare deploy token stored in $ENV_FILE."
fi
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
export CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_API_TOKEN
token_status=$(cloudflare_get "/accounts/$CLOUDFLARE_ACCOUNT_ID/tokens/verify" | cloudflare_field result.status 2>/dev/null || true)
if [[ "$token_status" != "active" ]]; then
  warn "Cloudflare did not accept the deploy token for account $CLOUDFLARE_ACCOUNT_ID (status: ${token_status:-unknown}). Check the account ID and the token, then re-run setup."
  exit 1
fi
ok "the deploy token is active for account $CLOUDFLARE_ACCOUNT_ID"
step "Install the exact dependencies recorded by Sylph."
bun install --frozen-lockfile
step "Point Alchemy at the deploy token instead of a browser login."
profile_method=$(alchemy_profile_method)
if [[ -z "$profile_method" ]]; then
  CI=true bunx alchemy login --configure
elif [[ "$profile_method" == "env" ]]; then
  ok "Alchemy's default profile already uses the credentials in $ENV_FILE"
else
  warn "Alchemy's default profile uses the $profile_method method, which ignores the deploy token in $ENV_FILE."
  if confirm "Switch Alchemy's default profile to the deploy token?"; then
    CI=true bunx alchemy login --configure
  else
    note "Deploys from this machine will keep using the $profile_method credentials."
  fi
fi
pause "Alchemy is configured. Press Enter to check the account."

stage "Account readiness"
say "Checking the account features Sylph needs before spending time on a deployment."
subdomain=$(cloudflare_get "/accounts/$CLOUDFLARE_ACCOUNT_ID/workers/subdomain" | cloudflare_field result.subdomain 2>/dev/null || true)
if [[ -z "$subdomain" ]]; then
  warn "This account has no workers.dev subdomain yet."
  open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
  step "Register a workers.dev subdomain under Workers & Pages."
  pause "Press Enter once the subdomain exists."
else
  ok "workers.dev subdomain: $subdomain.workers.dev"
fi
if cloudflare_get "/accounts/$CLOUDFLARE_ACCOUNT_ID/r2/buckets" | cloudflare_field success >/dev/null 2>&1; then
  ok "R2 is enabled"
else
  warn "R2 is not enabled or the deploy token cannot reach it."
  open_url "https://dash.cloudflare.com/?to=/:account/r2"
  step "Enable R2 for this account, then continue."
  pause "Press Enter once R2 is enabled."
fi
note "Durable Objects, Workflows, Containers, Browser Rendering, and Workers AI come with the Workers Paid plan."
note "Cloudflare Artifacts must be enabled for the account. Setup cannot probe it; the first deployment reports it if it is missing."
pause "The account looks ready. Press Enter to create the runtime credentials."

stage "Runtime credentials"
say "The deployed Worker gets its own narrower API token and an R2 key pair, both minted with the deploy token."
CF_TOKEN=$(_existing CF_TOKEN || true)
if [[ -z "$CF_TOKEN" ]]; then
  runtime_token=$(bun scripts/cloudflare-token.ts "Sylph runtime $(timestamp)" "$RUNTIME_TOKEN_PERMISSIONS")
  CF_TOKEN=$(printf '%s' "$runtime_token" | json_field value)
  ok "minted the runtime token"
else
  note "Reusing the runtime token stored in $ENV_FILE."
fi
write_env CF_TOKEN "$CF_TOKEN"
R2_ACCESS_KEY_ID=$(_existing R2_ACCESS_KEY_ID || true)
R2_SECRET_ACCESS_KEY=$(_existing R2_SECRET_ACCESS_KEY || true)
if [[ -z "$R2_ACCESS_KEY_ID" || -z "$R2_SECRET_ACCESS_KEY" ]]; then
  r2_token=$(bun scripts/cloudflare-token.ts "Sylph R2 $(timestamp)" "$R2_TOKEN_PERMISSIONS")
  R2_ACCESS_KEY_ID=$(printf '%s' "$r2_token" | json_field id)
  R2_SECRET_ACCESS_KEY=$(printf '%s' "$r2_token" | json_field secretAccessKey)
  ok "minted the R2 key pair"
else
  note "Reusing the R2 credentials stored in $ENV_FILE."
fi
write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
pause "Runtime credentials are ready. Press Enter to generate the Installation secrets."

stage "Installation secrets"
say "Generating the secrets that protect sessions, provider credentials, and the one-time Installation claim."
for key in BETTER_AUTH_SECRET CREDENTIAL_ENCRYPTION_KEY INSTALLATION_CLAIM_SECRET; do
  current=$(_existing "$key" || true)
  if [[ -z "$current" ]]; then
    current=$(openssl rand -hex 32)
  fi
  write_env "$key" "$current"
done
write_env ALLOW_TEST_MAGIC_LINKS "false"
note "The claim secret stays in $ENV_FILE and is entered once at /setup."
pause "Secrets are ready. Press Enter to deploy."

stage "Initial deployment"
say "The first deployment creates every Cloudflare resource and prints the permanent URL that GitHub OAuth needs."
note "A fresh account pulls and pushes the CI sandbox image, which can take several minutes with no progress output. Do not interrupt it."
deploy_log=$(mktemp)
bun alchemy deploy --stage prod --yes 2>&1 | tee "$deploy_log"
SYLPH_URL=$(deploy_url_from_log "$deploy_log")
rm -f "$deploy_log"
if [[ -n "$SYLPH_URL" ]]; then
  ok "deployed to $SYLPH_URL"
else
  step "Copy the website URL printed by Alchemy."
  ask SYLPH_URL "Paste the Sylph URL without a trailing slash:"
fi
SYLPH_URL="${SYLPH_URL%/}"
write_env SYLPH_URL "$SYLPH_URL"
if confirm "Will this Installation also act as the OAuth proxy for preview deployments? Most Installations answer no."; then
  OAUTH_PROXY_URL="$SYLPH_URL"
  OAUTH_PROXY_SECRET=$(_existing OAUTH_PROXY_SECRET || true)
  if [[ -z "$OAUTH_PROXY_SECRET" ]]; then
    OAUTH_PROXY_SECRET=$(openssl rand -hex 32)
  fi
  step "Choose a narrow HTTPS wildcard that matches only preview origins, such as https://sylph-*.${subdomain:-your-subdomain}.workers.dev."
  ask OAUTH_PROXY_TRUSTED_ORIGINS "Paste the trusted preview origin pattern:"
else
  OAUTH_PROXY_URL=""
  OAUTH_PROXY_SECRET=""
  OAUTH_PROXY_TRUSTED_ORIGINS=""
fi
write_env OAUTH_PROXY_URL "$OAUTH_PROXY_URL"
write_env OAUTH_PROXY_SECRET "$OAUTH_PROXY_SECRET"
write_env OAUTH_PROXY_TRUSTED_ORIGINS "$OAUTH_PROXY_TRUSTED_ORIGINS"
pause "The Installation is deployed. Press Enter to create the GitHub App."

stage "GitHub App"
say "Sylph uses one GitHub App for sign-in and repository-scoped Project access."
GITHUB_CLIENT_ID=$(_existing GITHUB_CLIENT_ID || true)
GITHUB_CLIENT_SECRET=$(_existing GITHUB_CLIENT_SECRET || true)
GITHUB_APP_URL=$(_existing GITHUB_APP_URL || true)
if [[ -n "$GITHUB_CLIENT_ID" && -n "$GITHUB_CLIENT_SECRET" ]]; then
  note "Reusing the GitHub App credentials stored in $ENV_FILE."
else
  ask SYLPH_GITHUB_APP_NAME "Name for the GitHub App (unique across GitHub):"
  ask SYLPH_GITHUB_APP_OWNER "GitHub organization that owns the App (blank for your personal account):"
  write_env SYLPH_GITHUB_APP_NAME "$SYLPH_GITHUB_APP_NAME"
  write_env SYLPH_GITHUB_APP_OWNER "$SYLPH_GITHUB_APP_OWNER"
  step "Your browser opens GitHub with the App pre-configured. Review it, then choose Create GitHub App."
  if app=$(SYLPH_URL="$SYLPH_URL" SYLPH_GITHUB_APP_NAME="$SYLPH_GITHUB_APP_NAME" SYLPH_GITHUB_APP_OWNER="$SYLPH_GITHUB_APP_OWNER" bun scripts/github-app-manifest.ts); then
    GITHUB_CLIENT_ID=$(printf '%s' "$app" | json_field clientId)
    GITHUB_CLIENT_SECRET=$(printf '%s' "$app" | json_field clientSecret)
    GITHUB_APP_URL=$(printf '%s' "$app" | json_field htmlUrl)
    ok "created $GITHUB_APP_URL"
  else
    warn "The manifest flow did not complete. Create the App by hand instead."
    open_url "https://github.com/settings/apps/new"
    step "Set GitHub App name to $SYLPH_GITHUB_APP_NAME"
    step "Set Homepage URL to $SYLPH_URL"
    step "Set Callback URL to $SYLPH_URL/api/auth/callback/github"
    step "Enable Request user authorization (OAuth) during installation."
    step "Disable Active under Webhook; Sylph synchronizes when Projects are opened, created, or accepted."
    step "Under Repository permissions, set Contents to Read and write and Pull requests to Read and write."
    step "Under Account permissions, set Email addresses to Read-only."
    step "Choose where this GitHub App can be installed, then create it."
    step "Copy the Client ID shown on the App settings page."
    ask GITHUB_CLIENT_ID "Paste the GitHub Client ID:"
    step "Generate a new client secret and copy it now."
    ask_secret GITHUB_CLIENT_SECRET "Paste the GitHub Client Secret:"
    GITHUB_APP_URL=""
  fi
fi
write_env GITHUB_CLIENT_ID "$GITHUB_CLIENT_ID"
write_env GITHUB_CLIENT_SECRET "$GITHUB_CLIENT_SECRET"
write_env GITHUB_APP_URL "$GITHUB_APP_URL"
if [[ -n "$GITHUB_APP_URL" ]]; then
  open_url "$GITHUB_APP_URL/installations/new"
else
  step "Open Install App in the GitHub App sidebar."
fi
step "Install the App and grant the repositories Sylph should access."
pause "The GitHub App is installed and its repositories are selected. Press Enter to continue."

stage "Production automation"
say "Publish the production configuration used by the Deploy production workflow in your fork."
if confirm "Publish production secrets and variables to this GitHub repository?"; then
  for name in BETTER_AUTH_SECRET CF_TOKEN CLOUDFLARE_API_TOKEN CREDENTIAL_ENCRYPTION_KEY GITHUB_CLIENT_SECRET INSTALLATION_CLAIM_SECRET OAUTH_PROXY_SECRET R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY; do
    if [[ -n "${!name}" ]]; then
      set_secret "$name" "${!name}"
    else
      note "skipped empty secret $name"
    fi
  done
  for name in CLOUDFLARE_ACCOUNT_ID GITHUB_CLIENT_ID OAUTH_PROXY_TRUSTED_ORIGINS OAUTH_PROXY_URL; do
    if [[ -n "${!name}" ]]; then
      set_var "$name" "${!name}"
    else
      note "skipped empty variable $name"
    fi
  done
else
  warn "Production automation was not configured. Run this setup again before relying on Deploy production."
fi
pause "Production automation is ready. Press Enter to continue."

stage "Launch and claim"
say "Redeploy with GitHub authentication, then claim the Installation with your own account."
bun alchemy deploy --stage prod --yes
open_url "$SYLPH_URL/setup"
step "Sign in with the GitHub account that should become the first Admin."
step "Confirm the verified email address shown by Sylph."
step "Enter an Organization name."
step "Copy INSTALLATION_CLAIM_SECRET from $ENV_FILE into the claim form."
step "Claim the Installation. Sylph creates the Organization and your owner membership together."
pause "Press Enter after the Installation has been claimed."

finish
