#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
USE_EXISTING_ENV_VALUES="${USE_EXISTING_ENV_VALUES:-true}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1 && tput clear 2>/dev/null; then return 0; fi
  printf '\033[2J\033[3J\033[H'
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ "$USE_EXISTING_ENV_VALUES" == "true" ]] || return 1
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "Sylph Installation setup"

if [[ -f "$ENV_FILE" ]]; then
  say "Setup found existing values in $ENV_FILE."
  if confirm "Reuse these values as defaults?"; then
    USE_EXISTING_ENV_VALUES="true"
    note "Existing values will be reused when you leave an answer blank."
  else
    USE_EXISTING_ENV_VALUES="false"
    note "Existing values will be ignored. New answers will replace matching values in $ENV_FILE."
  fi
  pause "Press Enter to continue."
fi

stage "Cloudflare account"
say "Sylph deploys to your Cloudflare account through Alchemy."
step "Alchemy will open Cloudflare so you can authorize this machine."
bunx alchemy login
step "Install the exact dependencies recorded by Sylph."
bun install --frozen-lockfile
pause "Cloudflare is connected and dependencies are installed. Press Enter to continue."

stage "Installation secrets"
say "We'll generate the secrets that protect sessions, provider credentials, and the one-time Installation claim."
for key in BETTER_AUTH_SECRET CREDENTIAL_ENCRYPTION_KEY INSTALLATION_CLAIM_SECRET OAUTH_PROXY_SECRET; do
  current=$(_existing "$key" || true)
  if [[ -z "$current" ]]; then
    current=$(openssl rand -hex 32)
  fi
  write_env "$key" "$current"
done
write_env ALLOW_TEST_MAGIC_LINKS "false"
note "The claim secret remains in .env and is entered once at /setup."
pause "Secrets are ready. Press Enter to deploy the bootstrap configuration."

stage "Cloudflare CI credentials"
say "Cloudflare CI needs a deployment token and R2 credentials inside its isolated Sandbox."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Choose Create Custom Token and name it Sylph CI."
step "Under Account permissions, add Account Settings Read, Account API Tokens Write, Workers Scripts Write, D1 Write, Workers R2 Storage Write, Containers Write, Workers CI Write, Workers AI Read, and Workers AI Write."
step "Under Account Resources, choose Include, Specific account, then select only this Sylph Installation's account. Do not add zone resources."
step "Create the token, then copy its value. Cloudflare shows it only once."
ask_secret CF_TOKEN "Paste the Cloudflare CI API token:"
write_env CF_TOKEN "$CF_TOKEN"
CLOUDFLARE_API_TOKEN="$CF_TOKEN"
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
open_url "https://dash.cloudflare.com/?to=/:account/r2/api-tokens"
step "Create an Account API token with Object Read & Write access to all buckets so the first deployment can create and use the generated Check backup bucket."
step "Copy the Account ID, Access Key ID, and Secret Access Key. Cloudflare shows the secret only once."
ask CLOUDFLARE_ACCOUNT_ID "Paste the Cloudflare Account ID:"
ask_secret R2_ACCESS_KEY_ID "Paste the R2 Access Key ID:"
ask_secret R2_SECRET_ACCESS_KEY "Paste the R2 Secret Access Key:"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
pause "Cloudflare CI credentials are ready. Press Enter to deploy the bootstrap configuration."

stage "Initial deployment"
say "The first deployment gives us the permanent URL required by GitHub OAuth."
bun alchemy deploy --stage prod
step "Copy the website URL printed by Alchemy."
ask SYLPH_URL "Paste the Sylph URL without a trailing slash:"
SYLPH_URL="${SYLPH_URL%/}"
write_env SYLPH_URL "$SYLPH_URL"
OAUTH_PROXY_URL="$SYLPH_URL"
write_env OAUTH_PROXY_URL "$OAUTH_PROXY_URL"
step "Choose a narrow HTTPS wildcard that matches only branch preview origins, such as https://sylph-*.your-subdomain.workers.dev."
ask OAUTH_PROXY_TRUSTED_ORIGINS "Paste the trusted branch origin pattern:"
write_env OAUTH_PROXY_TRUSTED_ORIGINS "$OAUTH_PROXY_TRUSTED_ORIGINS"

stage "GitHub App"
say "Create one GitHub App for sign-in and repository-scoped Project access."
open_url "https://github.com/settings/apps/new"
step "Set GitHub App name to a name that identifies this Sylph Installation."
step "Set Homepage URL to $SYLPH_URL"
step "Set Callback URL to $SYLPH_URL/api/auth/callback/github"
step "Enable Request user authorization (OAuth) during installation."
step "Disable Active under Webhook; Sylph synchronizes when Projects are opened, created, or accepted."
step "Under Repository permissions, set Contents to Read and write and Pull requests to Read and write."
step "Under Account permissions, set Email addresses to Read-only."
step "Choose where this GitHub App can be installed, then create it."
step "Copy the Client ID shown on the App settings page."
ask GITHUB_CLIENT_ID "Paste the GitHub Client ID:"
step "Generate a new client secret and copy it now."
ask_secret GITHUB_CLIENT_SECRET "Paste the GitHub Client Secret:"
write_env GITHUB_CLIENT_ID "$GITHUB_CLIENT_ID"
write_env GITHUB_CLIENT_SECRET "$GITHUB_CLIENT_SECRET"
step "Open Install App in the GitHub App sidebar, install it, and grant the repositories Sylph should access."
pause "The GitHub App is installed and its repositories are selected. Press Enter to continue."

stage "Production automation"
say "Publish the production configuration used by GitHub Actions."
if confirm "Publish production secrets and variables to this GitHub repository?"; then
  for name in BETTER_AUTH_SECRET CF_TOKEN CLOUDFLARE_API_TOKEN CREDENTIAL_ENCRYPTION_KEY GITHUB_CLIENT_SECRET INSTALLATION_CLAIM_SECRET OAUTH_PROXY_SECRET R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY; do
    set_secret "$name" "${!name}"
  done
  for name in CLOUDFLARE_ACCOUNT_ID GITHUB_CLIENT_ID OAUTH_PROXY_TRUSTED_ORIGINS OAUTH_PROXY_URL; do
    set_var "$name" "${!name}"
  done
else
  warn "Production automation was not configured. Run this setup again before relying on Deploy production."
fi
pause "Production automation is ready. Press Enter to continue."

stage "Launch and claim"
say "Redeploy with GitHub authentication, then claim the Installation with your own account."
bun alchemy deploy --stage prod
open_url "$SYLPH_URL/setup"
step "Sign in with the GitHub account that should become the first Admin."
step "Confirm the verified email address shown by Sylph."
step "Enter an Organization name."
step "Copy INSTALLATION_CLAIM_SECRET from .env into the claim form."
step "Claim the Installation. Sylph creates the Organization and your owner membership together."
pause "Press Enter after the Installation has been claimed."

finish
