#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
USE_EXISTING_ENV_VALUES="${USE_EXISTING_ENV_VALUES:-true}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1 && tput clear 2>/dev/null; then return 0; fi
  printf '\033[2J\033[3J\033[H'
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ "$USE_EXISTING_ENV_VALUES" == "true" ]] || return 1
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
umask 077
ENV_FILE="${SYLPH_SMOKE_ENV_FILE:-${XDG_CONFIG_HOME:-$HOME/.config}/sylph/release-smoke.env}"
mkdir -p "$(dirname "$ENV_FILE")"
ALCHEMY_PROFILE="${ALCHEMY_PROFILE:-$(_existing ALCHEMY_PROFILE || true)}"
if [[ -n "$ALCHEMY_PROFILE" ]]; then
  export ALCHEMY_PROFILE
fi

banner "Sylph release-smoke setup"

stage "Test identity"
say "Use the production deployment as the permanent OAuth proxy and a fresh stage for branch tests."
ask SYLPH_SMOKE_ADMIN_EMAIL "Verified email for the dedicated GitHub test account:"
write_env SYLPH_SMOKE_ADMIN_EMAIL "$SYLPH_SMOKE_ADMIN_EMAIL"
SYLPH_SMOKE_AUTH_STATE="${SYLPH_SMOKE_AUTH_STATE:-$(dirname "$ENV_FILE")/release-smoke-auth.json}"
write_env SYLPH_SMOKE_AUTH_STATE "$SYLPH_SMOKE_AUTH_STATE"
for key in BETTER_AUTH_SECRET CREDENTIAL_ENCRYPTION_KEY INSTALLATION_CLAIM_SECRET; do
  current=$(_existing "$key" || true)
  if [[ -z "$current" ]]; then
    current=$(openssl rand -hex 32)
  fi
  printf -v "$key" '%s' "$current"
  write_env "$key" "$current"
done
ALLOW_TEST_MAGIC_LINKS="false"
write_env ALLOW_TEST_MAGIC_LINKS "$ALLOW_TEST_MAGIC_LINKS"
pause "The test identity and Installation secrets are ready. Press Enter to continue."

stage "Cloudflare service account"
CLOUDFLARE_ACCOUNT_ID=$(_existing CLOUDFLARE_ACCOUNT_ID || true)
CLOUDFLARE_API_TOKEN=$(_existing CLOUDFLARE_API_TOKEN || true)
if [[ -n "$CLOUDFLARE_ACCOUNT_ID" && -n "$CLOUDFLARE_API_TOKEN" ]]; then
  note "Reusing the Cloudflare account ID and API token stored in $ENV_FILE."
else
  if [[ -z "$CLOUDFLARE_ACCOUNT_ID" ]]; then
    ask CLOUDFLARE_ACCOUNT_ID "Paste the Cloudflare Account ID:"
  fi
  if [[ -z "$CLOUDFLARE_API_TOKEN" ]]; then
    say "Create one durable account-owned token for this test Installation."
    open_url "https://dash.cloudflare.com/?to=/:account/api-tokens"
    step "Create an account-owned custom token. This requires Super Administrator access."
    step "Limit Account Resources to the Cloudflare account used for release-smoke."
    step "Add Account Settings Read, Account API Tokens Write, Workers Scripts Write, D1 Write, Workers R2 Storage Write, Workers Containers Write, Workers CI Write, Workers AI Read, Workers AI Write, Artifacts Write, and Browser Run Write."
    step "Create the token and copy it now. Cloudflare shows it only once."
    ask_secret CLOUDFLARE_API_TOKEN "Paste the account-owned API token:"
  fi
fi
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
CF_TOKEN="$CLOUDFLARE_API_TOKEN"
CLOUDFLARE_WORKERS_AI_TOKEN="$CLOUDFLARE_API_TOKEN"
write_env CF_TOKEN "$CLOUDFLARE_API_TOKEN"
write_env CLOUDFLARE_WORKERS_AI_TOKEN "$CLOUDFLARE_API_TOKEN"
pause "The reusable Cloudflare token is ready. Press Enter to continue."

stage "R2 credentials"
say "Alchemy creates stage-specific buckets. This wizard creates one reusable object token for every release-smoke bucket."
R2_ACCESS_KEY_ID=$(_existing R2_ACCESS_KEY_ID || true)
R2_SECRET_ACCESS_KEY=$(_existing R2_SECRET_ACCESS_KEY || true)
if [[ -n "$R2_ACCESS_KEY_ID" && -n "$R2_SECRET_ACCESS_KEY" ]]; then
  note "Reusing the R2 credentials stored in $ENV_FILE."
else
  command -v curl >/dev/null 2>&1 || { warn "curl is required to create R2 credentials."; exit 1; }
  command -v bun >/dev/null 2>&1 || { warn "bun is required to create R2 credentials."; exit 1; }

  permission_response=$(curl --silent --show-error \
    --get \
    --header "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    --data-urlencode "name=Workers R2 Storage Write" \
    --data-urlencode "scope=com.cloudflare.api.account" \
    "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/tokens/permission_groups")
  R2_PERMISSION_GROUP_ID=$(printf '%s' "$permission_response" | bun -e '
    const body = JSON.parse(await Bun.stdin.text())
    const group = body.result?.find(
      (entry) => entry.name === "Workers R2 Storage Write"
    )
    if (!body.success || !group?.id) {
      const detail = body.errors?.map((error) => error.message).join("; ")
      console.error(detail || "Cloudflare did not return the R2 account-write permission group")
      process.exit(1)
    }
    process.stdout.write(group.id)
  ')

  token_request=$(CLOUDFLARE_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID" R2_PERMISSION_GROUP_ID="$R2_PERMISSION_GROUP_ID" bun -e '
    const accountId = process.env.CLOUDFLARE_ACCOUNT_ID
    const permissionGroupId = process.env.R2_PERMISSION_GROUP_ID
    process.stdout.write(JSON.stringify({
      name: `Sylph release-smoke R2 ${new Date().toISOString()}`,
      policies: [{
        effect: "allow",
        resources: {
          [`com.cloudflare.api.account.${accountId}`]: "*"
        },
        permission_groups: [{ id: permissionGroupId }]
      }]
    }))
  ')
  token_response=$(curl --silent --show-error \
    --request POST \
    --header "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    --header "Content-Type: application/json" \
    --data "$token_request" \
    "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/tokens")
  R2_ACCESS_KEY_ID=$(printf '%s' "$token_response" | bun -e '
    const body = JSON.parse(await Bun.stdin.text())
    if (!body.success || !body.result?.id || !body.result?.value) {
      const detail = body.errors?.map((error) => error.message).join("; ")
      console.error(detail || "Cloudflare did not return a usable R2 token")
      process.exit(1)
    }
    process.stdout.write(body.result.id)
  ')
  R2_SECRET_ACCESS_KEY=$(printf '%s' "$token_response" | bun -e '
    import { createHash } from "node:crypto"
    const body = JSON.parse(await Bun.stdin.text())
    if (!body.success || !body.result?.value) {
      console.error("Cloudflare did not return the R2 token value")
      process.exit(1)
    }
    process.stdout.write(createHash("sha256").update(body.result.value).digest("hex"))
  ')
  write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
  write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
fi
pause "The R2 credentials are ready. Press Enter to configure the OAuth bridge."

stage "Production OAuth bridge"
say "Copy the OAuth bridge values from the production setup. This file reuses them for every smoke stage."
ask OAUTH_PROXY_URL "Paste the permanent proxy website URL without a trailing slash:"
OAUTH_PROXY_URL="${OAUTH_PROXY_URL%/}"
write_env OAUTH_PROXY_URL "$OAUTH_PROXY_URL"
ask OAUTH_PROXY_TRUSTED_ORIGINS "Paste the trusted branch origin pattern:"
write_env OAUTH_PROXY_TRUSTED_ORIGINS "$OAUTH_PROXY_TRUSTED_ORIGINS"
ask GITHUB_CLIENT_ID "Paste the production GitHub Client ID:"
ask_secret GITHUB_CLIENT_SECRET "Paste the production GitHub Client Secret:"
ask_secret OAUTH_PROXY_SECRET "Paste the production OAuth proxy secret:"
write_env GITHUB_CLIENT_ID "$GITHUB_CLIENT_ID"
write_env GITHUB_CLIENT_SECRET "$GITHUB_CLIENT_SECRET"
write_env OAUTH_PROXY_SECRET "$OAUTH_PROXY_SECRET"
pause "The production OAuth bridge is ready. Press Enter to finish the test configuration."

stage "Initial authentication"
say "The first headed smoke run stores GitHub browser state for later headless runs."
OPENROUTER_API_KEY=$(_existing OPENROUTER_API_KEY || true)
if [[ -n "$OPENROUTER_API_KEY" ]]; then
  note "Reusing the OpenRouter API key stored in $ENV_FILE."
else
  ask_secret OPENROUTER_API_KEY "Paste the OpenRouter API key:"
  write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
fi
step "Check the configuration: bun run smoke:release:doctor"
step "Deploy a fresh stage: bun run smoke:release:deploy"
step "Open the printed URL for manual verification, or add --headed to the printed test command."
step "Complete GitHub authentication when Playwright opens GitHub."
step "Later fresh-Installation runs reuse $SYLPH_SMOKE_AUTH_STATE."
note "gh auth is separate from the Playwright GitHub login."
chmod 600 "$ENV_FILE"

finish
